### PR TITLE
Add WSA Kernel `5.15.104.1`

### PR DESCRIPTION
**Pull request by s1204IT**
- Add `5.15.104.1`
- Delete `5.15.78.1`

### CODE REVIEW

**Comment by tiann** [comment]
Is this ready for merge?

**Comment by s1204IT** [comment]
Since the WSA with kernel version 5.15.104 has not yet been released, please leave the draft as is.
I'll contact you again once it is 2306 released and confirmed to work.

**Comment by YT-Advanced** [comment]
@tiann Now I think you can merge it !

**Review by tiann — APPROVED** [review]

**Comment by s1204IT** [comment]
@tiann 
https://github.com/tiann/KernelSU/actions/runs/5492616328#artifacts

Please release an additional kernel `5.15.104.1`.

**Pull request merged**
