### PR TITLE
Turkish translations of Root Templates

### PR DESCRIPTION
**Pull request by symbuzzer**

### CODE REVIEW

**Comment by JohnRTitor** [comment]
Aren't translations handled by [Weblate](https://hosted.weblate.org/engage/kernelsu/)? Or templates are just excluded?

**Comment by symbuzzer** [comment]
> Aren't translations handled by [Weblate](https://hosted.weblate.org/engage/kernelsu/)? Or templates are just excluded?

I cant see there, can you?

**Review by tiann — APPROVED** [review]

**Comment by tiann** [comment]
> Aren't translations handled by [Weblate](https://hosted.weblate.org/engage/kernelsu/)? Or templates are just excluded?

They are not in weblate now.

**Comment by symbuzzer** [comment]
@tiann Sir, I cant see translations still

**Pull request merged**
