### PR TITLE
Drop some legacy codes

### PR DESCRIPTION
**Pull request by yujincheng08**

### CODE REVIEW

**Review by Ylarod — APPROVED** [review]

**Comment by yujincheng08** [comment]
I dont think it affects manager.

**Comment by yujincheng08** [comment]
strange. these are only for mount. installing modules wont need mount.

**Comment by yujincheng08** [comment]
Oh forgot that installing modules requires mounting. But anyway it should be okay; it's time to drop more support for non-gki.

**Comment by chiteroman** [comment]
I can boot my 4.14 kernel without reverting this, is it really necessary to revert this commit?

**Comment by CanerKaraca23** [comment]
> I can boot my 4.14 kernel without reverting this, is it really necessary to revert this commit?

You can't install modules with this commit on non-gki.

**Pull request merged**
