### PR TITLE
setup.sh:change "obj-y"to"obj-$(CONFIG_KSU)"

### PR DESCRIPTION
**Pull request by dabao1955**
reference #570

I think it is maybe necessary.

### CODE REVIEW

**Comment by dabao1955** [comment]
It looks works well

**Comment by dpkg123** [comment]
Should I correct the following? shellcheck doesn't pass if I don't correct it. Although this has no effect on compilation:
change
```
printf "\nobj-$(CONFIG_KSU) += kernelsu/\n"
```
to
```
printf "obj-$(CONFIG_KSU) += %s\n" "kernelsu/"
```

**Comment by dabao1955** [comment]
change `printf "\nobj-$(CONFIG_KSU) += kernelsu/\n"`
to `printf "obj-$(CONFIG_KSU) += %s\n" "kernelsu/"`

Should I correct the following? shellcheck doesn't pass if I don't correct it. Although this has no effect on compilation.

**Comment by tiann** [comment]
Why close it? I think this is a good idea, but the method is not so accurate

**Comment by dabao1955** [comment]
> Why close it? I think this is a good idea, but the method is not so accurate

I think there's a little bit of a problem with that. Especially when KernelSU's Kconfig is inserted into drivers/Kconfigs, it doesn't look so coordinated.

See#582

**Comment by dabao1955** [comment]
> Why close it? I think this is a good idea, but the method is not so accurate



Maybe moving to the main menu is also a good option?

**Pull request closed without merging**
