### PR TITLE
website/docs/guide: Enable KernelSU support (CONFIG_KSU)

### PR DESCRIPTION
**Pull request by whyakari**
### enable CONFIG_KSU on the website documentation.

Added support for KernelSU by enabling CONFIG_KSU in the kernel defconfig located at `arch/arm64/configs/vendor/your_defconfig`. Please ensure to verify the correct location of the file. Note that on some devices, the defconfig may be located in `arch/arm64/configs`.

### CODE REVIEW

**Comment by tiann** [comment]
KernelSU doesn't support 32bit kernel

**Comment by whyakari** [comment]
> KernelSU doesn't support 32bit kernel

really, sorry. adjusted.

**Comment by whyakari** [comment]
Could you add CONFIG_KSU in the website documentation? without defining `#ifdef` and `#endif` between the hooks, it gives a compilation error, so it's good to add this in the documentation, as it helps other developers

**Comment by tiann** [comment]
> Could you add CONFIG_KSU in the website documentation? without defining `#ifdef` and `#endif` between the hooks, it gives a compilation error, so it's good to add this in the documentation, as it helps other developers

This is a good idea, just delete the description of 32bit is ok for this PR

**Review by tiann — APPROVED** [review]

**Pull request merged**
