### PR TITLE
Add android12-5.10-2023-11 (sublevel: 198) to CI build flow.

### PR DESCRIPTION
**Pull request by ArielHeleneto**
Add this kernel from https://source.android.com/docs/core/architecture/kernel/gki-android12-5_10-release-builds#november-2023-releases to CI

### CODE REVIEW

**Comment by ArielHeleneto** [comment]
tested on PHP110 ColorOS 14.0
Screenshot_2023-11-18-22-21-15-81_baaa51257c82a8b3f281ce09e6f2493f

**Comment by xiaocenter** [comment]
177  185   198间歇性断网解决没？红米k60   这个应该是通病

**Comment by ArielHeleneto** [comment]
> 177 185 198间歇性断网解决没？红米k60 这个应该是通病

hi 如果你愿意捐我一个红米k60的话，我可以帮你试试。

在此之前 我只能告诉你我的 Ace2V 没这毛病

**Comment by tiann** [comment]
Sorry, I've addd it https://github.com/tiann/KernelSU/commit/0db7aa573ed46b0016772dcbda9d9fff33def1be

**Pull request closed without merging**
