### PR TITLE
Added shizuku.root template

### PR DESCRIPTION
**Pull request by JohnRTitor**
Shizuku only needs DAC_OVERRIDE to execute the script to start the Shizuku service.
Also added bengali translation for the name and description.

### CODE REVIEW

**Comment by JohnRTitor** [comment]
Excuse me? Is there a reason it is closed?

**Comment by yujincheng08** [comment]
I think we can only gain shell permission for it.

**Comment by JohnRTitor** [comment]
You are right. It only needs to be part of the `shell` group. But it needs DAC_OVERRIDE permission to execute shell scripts. Else we'll get a permission error like this: 
Screenshot_20240201-220033_Shizuku


With the DAC_OVERRIDE and shell group, it can successfully start Shizuku service.

Screenshot_20240201-220712_KernelSU


You can test on your own if you want.

**Comment by JohnRTitor** [comment]
Can I update the commit and create another pull request?

**Comment by yujincheng08** [comment]
I reopened it. You can directly update it.

**Comment by JohnRTitor** [comment]
Updated, please check.

**Comment by tiann** [comment]
`DAC_READ_SEARCH` is enough, don't use `DAC_OVERRIDE`

**Comment by tiann** [comment]
I don't test if if can autostart when boot if we only give it `DAC_READ_SEARCH`

**Comment by JohnRTitor** [comment]
Tested and updated. Looks like it can do with `DAC_READ_SEARCH` Thanks!

**Review by tiann — APPROVED** [review]

**Pull request merged**
