### PR TITLE
Added adaway.root template

### PR DESCRIPTION
**Pull request by JohnRTitor**
Adaway only needs the following permissions to work properly: DAC_OVERRIDE, SYS_PTRACE.

Note: [systemless hosts kernelsu module](https://github.com/symbuzzer/systemless-hosts-KernelSU-module) needs to be installed, to add support.

This PR only addresses the minimal permission requirements of Adaway to let it modify hosts file.

### CODE REVIEW

**Comment by tiann** [comment]
Why needs `PTRACE`? please check: https://github.com/tiann/KernelSU/pull/1134#issuecomment-1807404954

**Comment by JohnRTitor** [comment]
> Why needs `PTRACE`? please check: [#1134 (comment)](https://github.com/tiann/KernelSU/pull/1134#issuecomment-1807404954)

To be honest, I just enabled all the permissions  and kept removing them till I got to this list. These permission are "essential" without these, the app can not seem to be modify the hosts file. 

If I just add it to the group `readproc` and remove the `PTRACE` perm:
Screenshot_20240204-204924_AdAway



Another thing I would like to note that there is a "Web server feature":
It needs to NET_BIND_SERVICE to work. (the certificate needs to be manually installed via certificate manager)
Screenshot_20240204-204326_AdAway

The app works fine with DAC_OVERRIDE, NET_BIND_SERVICE, SYS_PTRACE.

**Comment by tiann** [comment]
The `PTRACE` is a very dangerous cap, i don't know why it needs ptrace to work

**Comment by JohnRTitor** [comment]
Without this perm, the app can't seem to detect that it has root, on a fresh install/data cleared. I'm pinging  @symbuzzer here who contributed to both KernelSU and Adaway for their input. Also pinging an Adaway maintainer @PerfectSlayer

**Comment by symbuzzer** [comment]
It shouldn't need CAP_SYS_PTRACE I think. I also don't understand why it needs to read process

**Comment by symbuzzer** [comment]
I have no motivation for this, sorry ,:(

**Comment by PerfectSlayer** [comment]
Hey AdAway maintainer here 👋 

Not sure neither why `CAP_SYS _PTRACE` is needed but you get this error without it, it should mostly come from one of the two classes: [RootModel](https://github.com/AdAway/AdAway/blob/master/app/src/main/java/org/adaway/model/root/RootModel.java) or [ShellUtils](https://github.com/AdAway/AdAway/blob/master/app/src/main/java/org/adaway/model/root/ShellUtils.java).

It might also help if you are able to provide a logcat when it’s failing.

**Comment by JohnRTitor** [comment]
Here's the log snippet. 
[Log_2024-02-13_15-37-12.txt](https://github.com/tiann/KernelSU/files/14259499/Log_2024-02-13_15-37-12.txt)

I suppose this is the issue.
Screenshot_20240213-154016_Logcat Extreme~2

**Comment by symbuzzer** [comment]
@PerfectSlayer 
Wouldn't you consider creating the hosts file from the /data/data/org.adaway/files/ folder into the /data/adb/modules/systemless-hosts-KernelSU-module/system/etc/ folder? If KernelSU and systemless-hosts-KernelSU-module are installed, of course.

**Comment by tiann** [comment]
Although there are still some doubts, I will merge it; because it is better to have restrictions than no restrictions at all. If you find out why PTRACE is needed, you are welcome to PR again.

**Review by tiann — APPROVED** [review]

**Pull request merged**
