### PR TITLE
Build KernelSU as LKM

### PR DESCRIPTION
**Pull request by Ylarod**

### CODE REVIEW

**Review by tiann — APPROVED** [review]

**Comment by apathiquee** [comment]
Is the source code of the "ksuinit" file available somewhere? I'm trying to get the new LKM format on my device (Galaxy A54 5G) but it doesn't seem to work at all, the device is stuck at splash.

**Comment by Ylarod** [comment]
> Is the source code of the "ksuinit" file available somewhere? I'm trying to get the new LKM format on my device (Galaxy A54 5G) but it doesn't seem to work at all, the device is stuck at splash.

ksuinit is closed source

**Comment by tiann** [comment]
Nothing to do with ksuinit, you can try to disable KNOX first.

**Comment by BluCobalt** [comment]
> ksuinit is closed source

Is ksuinit always going to be closed source? Will it change when it is not new anymore?

**Comment by androiddisk** [comment]
> > Is the source code of the "ksuinit" file available somewhere? I'm trying to get the new LKM format on my device (Galaxy A54 5G) but it doesn't seem to work at all, the device is stuck at splash.
> 
> ksuinit is closed source

Hello, has ksuinit considered when to open source? My Moto SE50 can boot up after flashing kernelsu, but cannot enter recovery. It should be related to ksuinit. Thank you very much for your efforts

**Pull request merged**
