### PR TITLE
kernel: add prefix for functions in sepolicy

### PR DESCRIPTION
**Pull request by Ylarod**

### CODE REVIEW

**Comment by tiann** [comment]
can we use compiler extension like __always_inline？

**Comment by Ylarod** [comment]
ofc, but I think `static inline` is enough to solve problems like this
```
drivers/kernelsu/selinux/sepolicy.o: In function `allow':
sepolicy.c:(.text+0xec0): multiple definition of `allow'
drivers/clk/mediatek/clk-mt6853-pg.o:(.data+0x10): first defined here
/home/chen/android_kernel_xiaomi_cannon/Makefile:1144: recipe for target 'vmlinux' failed
make[1]: *** [vmlinux] Error 1
make[1]: Leaving directory '/home/chen/android_kernel_xiaomi_cannon/out'
Makefile:146: recipe for target 'sub-make' failed
make: *** [sub-make] Error 2
```

**Comment by tiann** [comment]
using `__always_inline`, we don't need to put all things to header file, and it is easier to maintain(maybe one day we want to export it?)

**Comment by Ylarod** [comment]
emm.. how to ?

**Review by tiann — APPROVED** [review]

**Review by tiann — APPROVED** [review]

**Pull request merged**
