### PR TITLE
kernel: Change CI build for WSA-5.10.117

### PR DESCRIPTION
**Pull request by longhuan1999**
1. The WSA kernel version has nothing to do with the Android version. Remove the Android version display
2. Merge x86_ 64 and arm64 strategy

### CODE REVIEW

**Comment by tiann** [comment]
By the way, can we just build the latest kernel?

**Comment by longhuan1999** [comment]
Before WSA use kernel 5.10.117.4-20221110(Android12), but now WSA use 5.10.117.2-20220906(Android13). I'm not sure which one they will choice in the next time.

**Comment by longhuan1999** [comment]
However, for the time being, we can choice  just build 5.10.117.2-20220906

**Comment by tiann** [comment]
Can any of a WSA kernel boot successfully?

**Comment by tiann** [comment]
What if the kernel version doesn't match? boot failed?

**Comment by longhuan1999** [comment]
I haven't done such tests.

**Comment by tiann** [comment]
Can you modify this PR again? After this PR, the compile time is twice as before, because we build arm64 and x86_64 in a job, but it was two job before. Although we half the `git clone`, we twice the compile time

**Comment by longhuan1999** [comment]
In this case, then how about modifing it to only compile the kernel version currently used by WAS at the same time?

**Comment by tiann** [comment]
i think this is a good idea

**Pull request merged**
