### PR TITLE
templates: Update templates and try to get rid with `CAP_SYS_ADMIN`

### PR DESCRIPTION
**Pull request by Rem01Gaming**
- The use of CAP_SYS_ADMIN can be avoided in Kernel Manager, but cannot be avoided in Root Explorer because it's needed for mounting RW/RO.
- Capabilities adjustment
- Fix template typo

### CODE REVIEW

**Comment by tiann** [comment]
What is the usage of `CAP_SYS_PTRACE`?

**Comment by Rem01Gaming** [comment]
Needed for see all running process

**Comment by tiann** [comment]
Add it to group `read_proc` is enough.

**Comment by Rem01Gaming** [comment]
Yes, I'm also thinking the same but FKM's perfmon doesn't shows all processes without it.
Attachment : 
[1]: FKM With `CAP_SYS_PTRACE` Screenshot_20231113-100349_Franco Kernel Manager
[2]: FKM Without `CAP_SYS_PTRACE` 
Screenshot_20231113-100438_Franco Kernel Manager

**Comment by Rem01Gaming** [comment]
Yes I'm also thinking the same thing but FKM's perfmon process doesn't displays all processes.

FKM with `CAP_SYS_PTRACE`
Screenshot_20231113-100349_Franco Kernel Manager
FKM without `CAP_SYS_PTRACE`

**Comment by tiann** [comment]
`groups: ["ROOT", "READPROC"]` should be ok

**Comment by Rem01Gaming** [comment]
> Yes I'm also thinking the same thing but FKM's perfmon process doesn't displays all processes.

It's working now
Screenshot_20231113-121715_Franco Kernel Manager

**Review by tiann — APPROVED** [review]

**Pull request merged**
