### PR TITLE
[add device] POCO X4 Pro, Redmi Note 11 Pro 5G

### PR DESCRIPTION
**Pull request by cachiusa**

### CODE REVIEW

**Comment by dereference23** [comment]
As the maintainer of this kernel, I ask to close this PR. KernelSU is included in the source tree for reference only and is not being built with the default configuration, nor is it shipped in any public distributions of this kernel.

**Comment by cachiusa** [comment]
At your discretion.

**Comment by cachiusa** [comment]
> not being built with the default configuration, nor is it shipped in any public distributions of this kernel.

1. KernelSU is enabled by default if you don't set it to `n` in default configuration.
2. Really? Never distrubuted publicly?

**Comment by dereference23** [comment]
> > not being built with the default configuration, nor is it shipped in any public distributions of this kernel.
> 
>     1. KernelSU is enabled by default
Not in this tree.

>     2. Really? Never distrubuted publicly?
Builds for internal testing are not public.

**Pull request closed without merging**
