### PR TITLE
ksud: Use fallback method to mount overlayfs when fsopen one failed

### PR DESCRIPTION
**Pull request by natsumerinchan**
Fix https://github.com/tiann/KernelSU/issues/1331 (Power by GPT-4.0)

### CODE REVIEW

**Comment by tiann** [comment]
I think the method of judging versions is not good enough, because some people may cherry pick; it should be judged if the statement is successful, if it fails, go to else, instead of just judging the first fsopen.

**Comment by natsumerinchan** [comment]
> I think the method of judging versions is not good enough, because some people may cherry pick; it should be judged if the statement is successful, if it fails, go to else, instead of just judging the first fsopen.

Done.

**Comment by tiann** [comment]
Sorry, I made a mistake and accidentally closed this PR. I have re-submitted it at https://github.com/tiann/KernelSU/commit/3829894d4d205642bb241fc5846463729e4d3eba and added you as a co-author. Sorry again.

**Comment by tiann** [comment]
I just don't why [this](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/committing-changes-to-a-pull-request-branch-created-from-a-fork) doesn't work :(

**Pull request closed without merging**
