### PR TITLE
CI: Fix arcvm root access,close #668

### LINKED ISSUE #668: ChromeOS arcvm中调用/system/bin/sh的应用无法正常使用root权限
**阐述bug**
ChromeOS上部分应用授权后实际上无法使用root权限，adb shell无法获取root权限
**复现步骤**
1.在ChromeOS安装KernelSU https://www.reddit.com/r/chromeos/comments/14bwi9r/tutorial_root_your_chromeos_android_subsystem/

2.为应用授权，但发现部分应用授权后实际上没有root权限

**预期行为**
所有应用都能正常授权

**截图**

photo_2023-06-20_17-39-55

**设备信息 :**
 - Device: x86_64 Desktop
 - OS: ChromeOS(brunch)
 - Version: chromeos_15393.58.0_volteer|brunch_r113_stable_20230603
 - KernelSU Version: https://github.com/tiann/KernelSU/commit/9b2f907a4848786b10cb37bf592c7905e3d87e02
 https://github.com/tiann/KernelSU/actions/runs/5318075425

**日志**

[KernelSU_bugreport_2023-06-20_17_34.tar.gz](https://github.com/tiann/KernelSU/files/11798785/KernelSU_bugreport_2023-06-20_17_34.tar.gz)

### PR DESCRIPTION
**Pull request by natsumerinchan**
It is caused by LTO.

### CODE REVIEW

**Comment by natsumerinchan** [comment]
Screenshot 2023-10-18 20 44 33

**Comment by natsumerinchan** [comment]
```
volteer_cheets:/ # cat /proc/kallsyms | grep vfs_*stat                                                                                                   
0000000000000000 t vfs_statx.llvm.12442327409394316677
0000000000000000 t vfs_statfs
0000000000000000 t show_vfsstat
0000000000000000 r __ksymtab_vfs_statfs
0000000000000000 r __kstrtabns_vfs_statfs
0000000000000000 r __kstrtab_vfs_statfs
volteer_cheets:/ # 
```

**Comment by tiann** [comment]
Can you send the `/proc/kallsyms`?

**Comment by natsumerinchan** [comment]
> Can you send the `/proc/kallsyms`? 你能发送 /proc/kallsyms 吗？

[kallsyms.txt](https://github.com/tiann/KernelSU/files/13027709/kallsyms.txt)

**Comment by tiann** [comment]
you can try `vfs_fstatat`

**Comment by tiann** [comment]
pass the macro by `make CFLAGS=-DUSE_VFS_STATX`
and check it by `defined(USE_VFS_STATX)`

**Comment by tiann** [comment]
> > pass the macro by `make CFLAGS=-DUSE_VFS_FSTATAT` and check it by `!defined(USE_VFS_FSTATAT)`通过使 CFLAGS=-DUSE_VFS_FSTATAT 传递宏 并通过！定义（USE_VFS_FSTATAT）进行检查
> 
> 试了但无效，有个最简单粗暴的方法是直接关掉LTO

无效是因为宏没有传递到代码里面？

**Comment by natsumerinchan** [comment]
> > > pass the macro by `make CFLAGS=-DUSE_VFS_FSTATAT` and check it by `!defined(USE_VFS_FSTATAT)`通过使 CFLAGS=-DUSE_VFS_FSTATAT 传递宏 并通过！定义（USE_VFS_FSTATAT）进行检查
> > 
> > 
> > 试了但无效，有个最简单粗暴的方法是直接关掉LTO
> 
> 无效是因为宏没有传递到代码里面？

不知，我现在删掉判定直接用vfs_fstatat试试

**Comment by natsumerinchan** [comment]
> > > > pass the macro by `make CFLAGS=-DUSE_VFS_FSTATAT` and check it by `!defined(USE_VFS_FSTATAT)`通过使 CFLAGS=-DUSE_VFS_FSTATAT 传递宏 并通过！定义（USE_VFS_FSTATAT）进行检查
> > > 
> > > 
> > > 试了但无效，有个最简单粗暴的方法是直接关掉LTO
> > 
> > 
> > 无效是因为宏没有传递到代码里面？
> 
> 不知，我现在删掉判定直接用vfs_fstatat试试

还是不行

**Comment by kalibyr-l33t** [comment]
Good work. I was about to come and use a collective batch of notes to fix some of these issues. But I waited a few hours... And then you came out of no where. Appreciate the effort. I'mma see what I can do to help out. If anything else you need I can do my best.

**Pull request closed without merging**
