### PR TITLE
WSA: 5.15.94.1

### PR DESCRIPTION
**Pull request by s1204IT**

### CODE REVIEW

**Comment by s1204IT** [comment]
This build is successful.
But, this doesn't seem to work.

**Comment by tiann** [comment]
> This build is successful. But, this doesn't seem to work.

What is wrong?

**Comment by tiann** [comment]
please try this commit

**Comment by s1204IT** [comment]
@tiann It worked!!
Thanks!

**Review by tiann — APPROVED** [review]

**Comment by s1204IT** [comment]
@tiann
Since MagiskOnWSA supports it, I would like you to publish it as a release.

https://github.com/LSPosed/MagiskOnWSALocal/pull/531
https://github.com/LSPosed/MagiskOnWSALocal/pull/529

**Comment by tiann** [comment]
> @tiann Since MagiskOnWSA supports it, I would like you to publish it as a release.
> 
> [LSPosed/MagiskOnWSALocal#531](https://github.com/LSPosed/MagiskOnWSALocal/pull/531) [LSPosed/MagiskOnWSALocal#529](https://github.com/LSPosed/MagiskOnWSALocal/pull/529)

will do it later

**Pull request merged**
