### PR TITLE
Revert "Drop some legacy codes (#1981)"

### PR DESCRIPTION
**Pull request by CanerKaraca23**
This reverts commit fd09ccfc2906ad119f7158f9518810e06a73a919.

So non-GKI users (0.9.5) can continue to use latest manager (ci for now).

This commit breaks installing modules on non-GKI manager users.

### CODE REVIEW

**Comment by CanerKaraca23** [comment]
> well, kernel needs fsopen for the new manager. ( no go for < 5.2 ) I guess they made their decision #1705

Yes, but devs don't dropped non-gki support for KSU manager after this announcement and drop commit.
https://github.com/tiann/KernelSU/commit/898e9d4f8ca9b2f46b0c6b36b80a872b5b88d899

This commit only breaks manager on non-gki kernel users, when you want to attempt installing module, it gives error and PR reverts this commit. This PR is not meant to bring back the non-gki support on KSU.

I wish @tiann will review this PR soon.

**Comment by Fede2782** [comment]
By only adding kernel code KernelSU worked fine in v1.0.1. Now this commit broke it and makes it impossible to benefit from new manager features (like action.sh) for non-GKI users. Now complete rebuild of everything is required for non-GKI devs.

**Comment by LeeBinder** [comment]
Dear @Fede2782, thank you for the explanation. I'm not around my secondary Nokia 6.1 (2018) legacy phone with Kernel Version 4.4.302-perf+ running crDroid 11 [KSU]/ Android 15 Official right now with [KernelSU Manager v1.0.1-20](https://github.com/user-attachments/files/18390416/KernelSU_v1.0.1-20-gbbc31bdb_11948-release.zip) (after first having to install Manager v.0.9.5 to "inject" older Kernel support into KSU Manager's data, then v.1.0.1 on-top).

So let me ask you remotely from afar: should the manager from your release https://github.com/Fede2782/KernelSU/releases/tag/v1.0.2-legacy be compatible with my phone and ROM, as is Manager v.1.0.1? Were you able to successfully not just re-integrate the missing code, but also make Manager v.1.0.2 work with Android kernels <4.14?

Thanks for your efforts - very much appreciated 👍

**Comment by LeeBinder** [comment]
YES, working, yee-ha 😀. Instructions see [here](https://github.com/tiann/KernelSU/issues/2130#issuecomment-2599404390) 😎

**Pull request closed without merging**
