### PR TITLE
Add support for ChromeOS ARM64 ARCVM

### PR DESCRIPTION
**Pull request by iceyear**
1. Add support for ChromeOS ARM64 ARCVM.
2. Optimization of intermediate variable naming.
3. Optimization of kernel version acquisition logic for file names, obtaining the kernel version directly from Makefile.

### CODE REVIEW

**Comment by YsLtr** [comment]
I have a arm device, hp chromebook x2 11. If possible, I can support to test it. This one https://github.com/gitiy1/KernelSU/actions/workflows/build-kernel-arcvm.yml is now not work properly on my device.

**Comment by gitiy1** [comment]
yeah, I have no ARM64 Soc Chromebook to test and it would be great if the developer could help us to collect logs and debug.

**Comment by iceyear** [comment]
yeah, I don't have access to an ARM64 SoC Chromebook for testing, so it would be incredibly helpful if the developer could assist us in collecting logs and debugging. While I can confirm that the workflow functions properly, there may still be code adjustments required for KernelSU

**Comment by YsLtr** [comment]
This is the `vmlinux` file in my device.
[vmlinux.zip](https://github.com/tiann/KernelSU/files/15021732/vmlinux.zip)

**Review by tiann — APPROVED** [review]

**Pull request merged**
