### PR TITLE
ci: use custom key to sign official bootimgs

### PR DESCRIPTION
**Pull request by Ylarod**
We can get pub key hash by 
```
avbtool info_image --image boot.img
```

### CODE REVIEW

**Comment by tiann** [comment]
how to generate `BOOT_SIGN_KEY` ?

**Comment by Ylarod** [comment]
```
openssl genrsa -out rsa_private_key.pem 2048
```

**Comment by tiann** [comment]
Is Magisk use a custom key to sign boot or only use test key?

**Comment by Ylarod** [comment]
> Is Magisk use a custom key to sign boot or only use test key?

seems no.
https://github.com/topjohnwu/Magisk/blob/master/tools/keys/

**Pull request merged**
