### PR TITLE
some Kconfig patches

### PR DESCRIPTION
**Pull request by ookiineko**

### CODE REVIEW

**Comment by tiann** [comment]
how the config is used？

**Comment by ookiineko** [comment]
in `menuconfig`

**Comment by ookiineko** [comment]
CONFIG_OVERLAY_FS is now automatically selected by CONFIG_KSU

**Comment by ookiineko** [comment]
when CONFIG_KSU_NO_KPROBE is enabled, users can leave CONFIG_KPROBES disabled

**Comment by ookiineko** [comment]
i also changed the option type of CONFIG_KSU_DEBUG from tristate to bool, bcs it is just a debug flag, should never be set to =m

**Comment by ookiineko** [comment]
bcs it does not make sense

**Comment by ookiineko** [comment]
in that case

**Comment by ookiineko** [comment]
> when CONFIG_KSU_NO_KPROBE is enabled, users can leave CONFIG_KPROBES disabled

without CONFIG_KSU_NO_KPROBE, users won't be able to find CONFIG_KSU in the kernel config menu unless they turn the CONFIG_KPROBES on

**Comment by ookiineko** [comment]
demo

[2023-01-27 13-02-47.mkv.tar.gz](https://github.com/tiann/KernelSU/files/10515749/2023-01-27.13-02-47.mkv.tar.gz)

**Comment by ookiineko** [comment]
changed the type of CONFIG_KSU to bool as well, or need changes to the Makefiles

but is it actually useful if KSU is compiled as a kernel module?

**Comment by tiann** [comment]
Just modify the Kconfig is not enough, because this config is unused in main branch.

**Comment by ookiineko** [comment]
> Just modify the Kconfig is not enough, because this config is unused in main branch.

true, need to modify the Makefile as well, closing for now

**Pull request closed without merging**
